directories:
  output: release
  buildResources: build
appId: com.sleepyfox.app
productName: sleepyfox
files:
  - filter:
      - dist/**/*
      - index.js
      - sleepyfox.ico
      - sleepyfox.png
win:
  icon: sleepyfox.ico
  target: nsis
electronVersion: 32.0.0
